version: '3'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - snappfood/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_admin
      - POSTGRES_PASSWORD=django_admin
      - POSTGRES_DB=django_dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web
    ports:
      - "80:80"
volumes:
  postgres_data:
  static_volume:
  media_volume: